# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'server_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16server_streaming.proto\x12\x0cserverstream\"\x1e\n\rNumberRequest\x12\r\n\x05start\x18\x01 \x01(\x05\" \n\x0eNumberResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32_\n\rNumberService\x12N\n\x0fGenerateNumbers\x12\x1b.serverstream.NumberRequest\x1a\x1c.serverstream.NumberResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERREQUEST']._serialized_start=40
  _globals['_NUMBERREQUEST']._serialized_end=70
  _globals['_NUMBERRESPONSE']._serialized_start=72
  _globals['_NUMBERRESPONSE']._serialized_end=104
  _globals['_NUMBERSERVICE']._serialized_start=106
  _globals['_NUMBERSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
