# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import server_streaming_pb2 as server__streaming__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server_streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NumberServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateNumbers = channel.unary_stream(
                '/serverstream.NumberService/GenerateNumbers',
                request_serializer=server__streaming__pb2.NumberRequest.SerializeToString,
                response_deserializer=server__streaming__pb2.NumberResponse.FromString,
                _registered_method=True)


class NumberServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateNumbers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NumberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateNumbers': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateNumbers,
                    request_deserializer=server__streaming__pb2.NumberRequest.FromString,
                    response_serializer=server__streaming__pb2.NumberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serverstream.NumberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('serverstream.NumberService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NumberService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/serverstream.NumberService/GenerateNumbers',
            server__streaming__pb2.NumberRequest.SerializeToString,
            server__streaming__pb2.NumberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
