# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: download.proto

require 'google/protobuf'


descriptor_data = "\n\x0e\x64ownload.proto\x12\x08\x64ownload\"$\n\x0f\x44ownloadRequest\x12\x11\n\tvideo_url\x18\x01 \x01(\t\"s\n\x16\x44ownloadStatusResponse\x12\x1d\n\x13progress_percentage\x18\x01 \x01(\x02H\x00\x12\x17\n\rfinal_message\x18\x02 \x01(\tH\x00\x12\x17\n\rerror_message\x18\x03 \x01(\tH\x00\x42\x08\n\x06status\"O\n\x15VideoMetadataResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\x12\x15\n\rthumbnail_url\x18\x03 \x01(\t2\xb1\x01\n\x0f\x44ownloadService\x12N\n\x10GetVideoMetadata\x12\x19.download.DownloadRequest\x1a\x1f.download.VideoMetadataResponse\x12N\n\rDownloadVideo\x12\x19.download.DownloadRequest\x1a .download.DownloadStatusResponse0\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Download
  DownloadRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("download.DownloadRequest").msgclass
  DownloadStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("download.DownloadStatusResponse").msgclass
  VideoMetadataResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("download.VideoMetadataResponse").msgclass
end
