# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: download.proto for package 'download'

require 'grpc'
require 'download_pb'

module Download
  module DownloadService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'download.DownloadService'

      rpc :GetMetadata, ::Download::Request, ::Download::Metadata
      rpc :GetFile, ::Download::Request, stream(::Download::DownloadChunk)
    end

    Stub = Service.rpc_stub_class
  end
end
