# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: download.proto for package 'download'

require 'grpc'
require 'download_pb'

module Download
  module DownloadService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'download.DownloadService'

      rpc :GetVideoMetadata, ::Download::DownloadRequest, ::Download::VideoMetadataResponse
      rpc :DownloadVideo, ::Download::DownloadRequest, stream(::Download::DownloadStatusResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
