# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: playlist.proto for package 'playlist'

require 'grpc'
require_relative 'playlist_pb'

module Playlist
  module PlaylistService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'playlist.PlaylistService'

      rpc :GetPlaylists, ::Playlist::Empty, ::Playlist::Playlists
      rpc :GetPlaylistsById, ::Playlist::PlaylistId, ::Playlist::Playlist
      rpc :PostPlaylists, ::Playlist::PlaylistInfo, ::Playlist::PlaylistId
      rpc :PatchPlaylists, ::Playlist::PlaylistPatchInfo, ::Playlist::PlaylistId
      rpc :DeletePlaylists, ::Playlist::PlaylistId, ::Playlist::Empty
      rpc :GetVideosById, ::Playlist::VideoId, ::Playlist::Video
      rpc :PostVideos, ::Playlist::VideoPostInfo, ::Playlist::VideoId
      rpc :DeleteVideos, ::Playlist::VideoId, ::Playlist::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
