# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client_streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'client_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63lient_streaming.proto\x12\x0c\x63lientstream\"\x1f\n\rNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\"\n\x0f\x41verageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2^\n\x0cStatsService\x12N\n\x0e\x43omputeAverage\x12\x1b.clientstream.NumberRequest\x1a\x1d.clientstream.AverageResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERREQUEST']._serialized_start=40
  _globals['_NUMBERREQUEST']._serialized_end=71
  _globals['_AVERAGERESPONSE']._serialized_start=73
  _globals['_AVERAGERESPONSE']._serialized_end=107
  _globals['_STATSSERVICE']._serialized_start=109
  _globals['_STATSSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
