# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: download.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'download.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ownload.proto\x12\x08\x64ownload\"\x16\n\x07Request\x12\x0b\n\x03url\x18\x01 \x01(\t\"W\n\x08Metadata\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\x12\x15\n\rthumbnail_url\x18\x03 \x01(\t\x12\x13\n\x0btotal_bytes\x18\x04 \x01(\x03\"?\n\x0eProgressUpdate\x12\x18\n\x10\x62ytes_downloaded\x18\x01 \x01(\x03\x12\x13\n\x0btotal_bytes\x18\x02 \x01(\x03\"X\n\rDownloadChunk\x12,\n\x08progress\x18\x01 \x01(\x0b\x32\x18.download.ProgressUpdateH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload2\x80\x01\n\x0f\x44ownloadService\x12\x34\n\x0bGetMetadata\x12\x11.download.Request\x1a\x12.download.Metadata\x12\x37\n\x07GetFile\x12\x11.download.Request\x1a\x17.download.DownloadChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'download_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=28
  _globals['_REQUEST']._serialized_end=50
  _globals['_METADATA']._serialized_start=52
  _globals['_METADATA']._serialized_end=139
  _globals['_PROGRESSUPDATE']._serialized_start=141
  _globals['_PROGRESSUPDATE']._serialized_end=204
  _globals['_DOWNLOADCHUNK']._serialized_start=206
  _globals['_DOWNLOADCHUNK']._serialized_end=294
  _globals['_DOWNLOADSERVICE']._serialized_start=297
  _globals['_DOWNLOADSERVICE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
