# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: download.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'download.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ownload.proto\x12\x08\x64ownload\"$\n\x0f\x44ownloadRequest\x12\x11\n\tvideo_url\x18\x01 \x01(\t\"s\n\x16\x44ownloadStatusResponse\x12\x1d\n\x13progress_percentage\x18\x01 \x01(\x02H\x00\x12\x17\n\rfinal_message\x18\x02 \x01(\tH\x00\x12\x17\n\rerror_message\x18\x03 \x01(\tH\x00\x42\x08\n\x06status\"O\n\x15VideoMetadataResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\x12\x15\n\rthumbnail_url\x18\x03 \x01(\t2\xb1\x01\n\x0f\x44ownloadService\x12N\n\x10GetVideoMetadata\x12\x19.download.DownloadRequest\x1a\x1f.download.VideoMetadataResponse\x12N\n\rDownloadVideo\x12\x19.download.DownloadRequest\x1a .download.DownloadStatusResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'download_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOWNLOADREQUEST']._serialized_start=28
  _globals['_DOWNLOADREQUEST']._serialized_end=64
  _globals['_DOWNLOADSTATUSRESPONSE']._serialized_start=66
  _globals['_DOWNLOADSTATUSRESPONSE']._serialized_end=181
  _globals['_VIDEOMETADATARESPONSE']._serialized_start=183
  _globals['_VIDEOMETADATARESPONSE']._serialized_end=262
  _globals['_DOWNLOADSERVICE']._serialized_start=265
  _globals['_DOWNLOADSERVICE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
