# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: playlist.proto for package 'playlist'

require 'grpc'
require 'playlist_pb'

module Playlist
  module PlaylistService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'playlist.PlaylistService'

      rpc :CreatePlaylist, ::Playlist::CreatePlaylistRequest, ::Playlist::PlaylistResponse
      rpc :GetPlaylist, ::Playlist::GetPlaylistRequest, ::Playlist::PlaylistResponse
      rpc :ListPlaylists, ::Playlist::ListPlaylistsRequest, ::Playlist::ListPlaylistsResponse
      rpc :EditPlaylist, ::Playlist::EditPlaylistRequest, ::Playlist::PlaylistResponse
      rpc :DeletePlaylist, ::Playlist::DeletePlaylistRequest, ::Playlist::ListPlaylistsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
